---
- name: Ensure .bashrc is sourcing .bash_profile
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "source {{ ansible_user_dir }}/.bash_profile"
    state: present

- name: Copy bash config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "bash"
    mode: 0644
    directory_mode: 0755
    force: true

- name: Copy .bash_profile
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/"
    src: ".bash_profile"
    mode: 0644
    force: true

- name: Set default
  user:
    name: "{{ host_user }}"
    shell: /usr/bin/bash
  become: true

- name: Set public
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.bash_public"
    src: ".bash_public.j2"
    mode: 0644

- name: Set private
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.bash_private"
    src: ".bash_private.j2"
    mode: 0644
  no_log: true
