---
- name: Detect oh-my-bash
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-bash"
  register: ohmybash

- name: Register oh-my-bash state
  ansible.builtin.set_fact:
    ohmybash_is_installed: "{{ ohmybash.stat.exists }}"

- name: Debug ohmybash_is_installed
  ansible.builtin.debug:
    var: ohmybash_is_installed

- name: Upgrade oh-my-bash
  block:
    - name: Run Upgrade oh-my-bash script
      ansible.builtin.script:
        cmd: "{{ ansible_user_dir }}/.oh-my-bash/tools/upgrade.sh"
  when: ohmybash_is_installed

- name: Install oh-my-bash
  block:
    - name: Download oh-my-bash Install Script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh
        dest: /tmp/oh-my-bash.install.sh
        force: true
        mode: 0755
    - name: Run the install script
      ansible.builtin.script:
        cmd: /tmp/oh-my-bash.install.sh
  when: not ohmybash_is_installed

- name: Copy .bashrc
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: 0644

- name: Copy custom bash config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "bash"
    mode: 0644
    directory_mode: 0755
    force: true

- name: Set default
  user:
    name: "{{ host_user }}"
    shell: /usr/bin/bash
  become: true

- name: Set private
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/bash/.bash_private"
    src: ".bash_private.j2"
    mode: 0644
  no_log: true
