---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/bash"
    state: directory

- name: Copy bash config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash"
    src: "bash"
    mode: 0644
    directory_mode: 0644
    force: true

- name: Copy .bash_profile
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/"
    src: ".bash_profile"
    mode: 0644
    force: true
