---
- hosts: localhost

  pre_tasks:
    - name: Set package state variables
      import_tasks: pre_tasks/package_state.yaml

    - name: Detect WSL
      import_tasks: pre_tasks/detect_wsl.yaml connection: local

  tasks:
    - name: set roles
      set_fact:
        roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      debug: "var=roles"
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always
