---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect WSL
      import_tasks: pre_tasks/detect_wsl.yml

    - name: detect_wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl

    - name: Detect Host User
      import_tasks: pre_tasks/whoami.yml

  tasks:
    - name: set roles
      set_fact:
        roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      debug: "var=roles"
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always
