---
- name: Update APT Repos and Upgrade APT Packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
    autoremove: true
    autoclean: true
  become: true

- name: Install
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
    state: present
  become: true

- name: Set sudo
  ansible.builtin.template:
    src: user-sudo.j2
    dest: "/etc/sudoers.d/{{ ansible_env['USER'] }}"
    mode: 0644
  become: true

- name: Set hosts
  ansible.builtin.template:
    dest: "/etc/hosts"
    src: hosts.j2
    mode: 0644
  become: true
  when: not ansible_host_environment_is_wsl
