---
- name: Get latest release of a public repository
  community.general.github_release:
    user: ansible
    repo: ansible
    action: latest_release
  register: latest_go_release

- name: Generate go file name
  ansible.builtin.set_fact:
    go_file: "go{{ latest_go_release }}.linux-amd64"

- name: Download GitHub Release
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/golang/{{ go_file }}.tar.gz"
    dest: /tmp
    mode: 0644
    force: true
  when: ansible_architecture == "x86_64" or ansible_architecture == "amd64"
  notify:
    - Cleanup go downloaded tar

- name: Extract go tar file
  ansible.builtin.unarchive:
    src: "/tmp/{{ go_file }}.tar.gz"
    dest: /tmp
    mode: 0644
  
