---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: "Neovim | Install"
  ansible.builtin.apt:
    name: neovim
    state: present
  become: true

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim | Copy init.lua"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
    src: "init.lua"
    mode: 0644

- name: "Neovim | Copy .luarc.json"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/.luarc.json"
    src: ".luarc.json"
    mode: 0644

- name: "Neovim | Copy modules"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"
    src: "lua/"
    mode: "0644"

- name: "Neovim | Get config files"
  ansible.builtin.find:
    paths: "{{ ansible_role_path }}/files/lua"
    file_type: file
  register: config_files

- name: Find all remote files
  ansible.builtin.find:
    paths: "{{ ansible_user_dir }}/.config/nvim/lua"
    file_type: file
  register: existing

- name: "Neovim | Delete any leftover files"
  ansible.builtin.file:
    path: {{ item.path }}
    state: absent
  when: item.path|basename not in config_files.files|map(attribute='path')|list
  with_items: "{{existing.files|default([ ])}}"
  register: removed

